- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Cog
  - Core
  - Elkridge
  - Fland
  #- Gate
  #- Loop # Harmony, commented out due to technical issues 
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Packed
  - Reach
  #- Train
  # Harmony
  - Aspid
  - Barratry
  - Atlas
